version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fluxpay-app
    container_name: fluxpay-app
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - fluxpay

  web:
    image: nginx:alpine
    container_name: fluxpay-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fluxpay

  db:
    image: mysql:8.0
    container_name: fluxpay-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fluxpay
      MYSQL_USER: fluxuser
      MYSQL_PASSWORD: fluxpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - fluxpay

volumes:
  dbdata:

networks:
  fluxpay:
