version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fluxpay_app
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - fluxpay_net

  mysql:
    image: mysql:8
    container_name: fluxpay_mysql
    restart: always
    environment:
      MYSQL_DATABASE: fluxpay
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fluxuser
      MYSQL_PASSWORD: fluxpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fluxpay_net

  nginx:
    image: nginx:alpine
    container_name: fluxpay_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fluxpay_net

volumes:
  mysql_data:

networks:
  fluxpay_net:
